/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;

import javax.swing.JOptionPane;
import java.util.regex.*;
import java.sql.*;
import java.util.logging.Level;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Logger;

/**
 *
 * @author Kinchit
 */
public class AdminDeposit extends javax.swing.JPanel {

    /**
     * Creates new form AdminDeposit
     */
    public AdminDeposit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TextFieldAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonDeposit = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        TextFieldAmount.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 98);
        add(TextFieldAmount, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deposit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 173, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Enter Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 96, 0, 0);
        add(jLabel2, gridBagConstraints);

        ButtonDeposit.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        ButtonDeposit.setText("Deposit");
        ButtonDeposit.setName(""); // NOI18N
        ButtonDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonDepositMouseClicked(evt);
            }
        });
        ButtonDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDepositActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 145;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 96, 128, 98);
        add(ButtonDeposit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDepositMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ButtonDepositMouseClicked

    private void ButtonDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDepositActionPerformed
        // TODO add your handling code here:
        if(Pattern.matches("\\d+",TextFieldAmount.getText())){
            int amount=Integer.parseInt(TextFieldAmount.getText());
            try{
                Connection con=DriverManager.getConnection(ATM.url);
                con.setAutoCommit(false);
                Statement statement = con.createStatement();
                String sql="select count(*) from transactions";
                ResultSet result=statement.executeQuery(sql);
                result.next();
                int count=result.getInt(1);
                count++;
                sql="insert into transactions values(?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setInt(1, count);
                ps.setString(2,"0000");
                ps.setDate(3, Date.valueOf(LocalDate.now()));
                ps.setTime(4, Time.valueOf(LocalTime.now()));
                ps.setString(5, "debit");
                ps.setString(6, "admin");
                ps.setInt(7, amount);
                int flag=ps.executeUpdate();
                if(flag!=1){
                    JOptionPane.showMessageDialog(ButtonDeposit,"Transaction Failed", "Deposit", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                sql="select balance from accounts where name='admin'";
                result=statement.executeQuery(sql);
                result.next();
                int balance = result.getInt(1);
                int newBalance = amount + balance;
                sql="update accounts set balance="+newBalance+" where name='admin'";
                flag=statement.executeUpdate(sql);
                if(flag==1){
                    JOptionPane.showMessageDialog(ButtonDeposit, "Transaction Successful", "Deposit", JOptionPane.INFORMATION_MESSAGE);
                    con.commit();
                    AdminPanel panel = new AdminPanel();
                    ATM.panelSwap(this,panel);
                }else{
                    JOptionPane.showMessageDialog(ButtonDeposit,"Transaction Failed", "Deposit", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminDeposit.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(ButtonDeposit, "Please enter a valid amount", "Deposit", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonDepositActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDeposit;
    private javax.swing.JTextField TextFieldAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
