/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kinchit
 */
public class BillPayment extends javax.swing.JPanel {

    private String acc_no;

    /**
     * Creates new form BillPayment
     */
    public BillPayment(String acc_no) {
        this.acc_no = acc_no;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldAmount = new javax.swing.JTextField();
        comBoxParty = new javax.swing.JComboBox<>();
        buttonPay = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Payment To");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 102, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("Amount");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 138, 0, 0);
        add(jLabel3, gridBagConstraints);

        textFieldAmount.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 91);
        add(textFieldAmount, gridBagConstraints);

        comBoxParty.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        comBoxParty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vi India", "BSNL", "Jio", "MSEB" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 91);
        add(comBoxParty, gridBagConstraints);

        buttonPay.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        buttonPay.setText("Pay");
        buttonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 174, 56, 0);
        add(buttonPay, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/icons8-bill-32.png"))); // NOI18N
        jLabel4.setText("Bill Payment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 119, 0, 0);
        add(jLabel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPayActionPerformed
        // TODO add your handling code here:
        if (!Pattern.matches(ATM.regexAmount, textFieldAmount.getText())) {
            JOptionPane.showMessageDialog(buttonPay, "Please enter a valid amount ", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long amount = Long.parseLong(textFieldAmount.getText());
        try {
            Connection con = DriverManager.getConnection(ATM.url);
            con.setAutoCommit(false);
            Statement statement = con.createStatement();
            ResultSet res = statement.executeQuery("select count(*) from bills");
            res.next();
            String id = res.getString(1) + 1;
            String sql = "select count(*) from transactions";
            res = statement.executeQuery(sql);
            res.next();
            int count = res.getInt(1) + 1;
            sql = "insert into transactions values(?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, count);
            ps.setString(2, acc_no);
            ps.setDate(3, Date.valueOf(LocalDate.now()));
            ps.setTime(4, Time.valueOf(LocalTime.now()));
            ps.setString(5, "credit");
            ps.setString(6, comBoxParty.getSelectedItem().toString());
            ps.setLong(7, amount);
            int flag = ps.executeUpdate();
            if (flag != 1) {
                JOptionPane.showMessageDialog(this, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            res = statement.executeQuery("select c_id from accounts where acc_no=" + acc_no);
            res.next();
            int c_id = res.getInt(1);
            sql = "insert into bills values(?,?,?,?,?,?,?)";
            ps = con.prepareStatement(sql);
            ps.setString(1, id);
            ps.setDate(2, Date.valueOf(LocalDate.now()));
            ps.setTime(3, Time.valueOf(LocalTime.now()));
            ps.setString(4, comBoxParty.getSelectedItem().toString());
            ps.setLong(5, amount);
            ps.setInt(6, count);
            ps.setInt(7, c_id);
            flag = ps.executeUpdate();
            if (flag != 1) {
                JOptionPane.showMessageDialog(this, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql = "select balance from accounts where acc_no='0000'";
            res = statement.executeQuery(sql);
            res.next();
            long cash = res.getLong(1);
            cash = cash - amount;
            sql = "update accounts set balance=" + cash + " where acc_no='0000'";
            flag = statement.executeUpdate(sql);
            if (flag != 1) {
                JOptionPane.showMessageDialog(this, "Transaction Failed", "Withdraw", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql = "select balance from accounts where acc_no='" + acc_no + "'";
            res = statement.executeQuery(sql);
            res.next();
            long balance = res.getLong(1) - amount;
            sql = "update accounts set balance=" + balance + " where acc_no='" + acc_no + "'";
            flag = statement.executeUpdate(sql);
            if (flag != 1) {
                JOptionPane.showMessageDialog(this, "Transaction Failed", "Withdraw", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Transaction Successful\nReceipt will be generated", this.getName(), JOptionPane.INFORMATION_MESSAGE);
            String reportPath = "C:\\Users\\Kinchit\\JaspersoftWorkspace\\MyReports\\Receipt.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            HashMap param = new HashMap();
            param.put("t_id", count);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jv.enable();
            jv.setVisible(true);
            con.commit();
            ATM.panelSwap(this, new Home());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPay;
    private javax.swing.JComboBox<String> comBoxParty;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textFieldAmount;
    // End of variables declaration//GEN-END:variables
}
