/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Kinchit
 */
public class CheckBalance extends javax.swing.JPanel {

    /**
     * Creates new form CheckBalance
     */
    public CheckBalance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldAcc = new javax.swing.JTextField();
        buttonCheck = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/icons8-sales-balance-1-32.png"))); // NOI18N
        jLabel1.setText("Check Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 91, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Account No:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 47, 0, 0);
        add(jLabel2, gridBagConstraints);

        textFieldAcc.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 51);
        add(textFieldAcc, gridBagConstraints);

        buttonCheck.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        buttonCheck.setText("Check");
        buttonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCheckActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 152, 73, 0);
        add(buttonCheck, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCheckActionPerformed
        // TODO add your handling code here:
        String acc=textFieldAcc.getText();
        if(!Pattern.matches(ATM.regexAcc, acc)){
            JOptionPane.showMessageDialog(buttonCheck, "Please enter a valid account number", "", JOptionPane.ERROR_MESSAGE);
            return;
        }try{
            Connection con=DriverManager.getConnection(ATM.url);
            Statement statement=con.createStatement();
            String sql="select balance from accounts where acc_no="+acc;
            ResultSet res=statement.executeQuery(sql);
            if(!res.next()){
                JOptionPane.showMessageDialog(buttonCheck, "Not found", "", JOptionPane.ERROR_MESSAGE);
            return;
            }
            String balance=Integer.toString(res.getInt(1));
            JOptionPane.showMessageDialog(buttonCheck, "Balance = ₹"+balance, "", JOptionPane.INFORMATION_MESSAGE);
            ATM.panelSwap(this, new Home());
        }catch(Exception e) {e.printStackTrace();}
        
    }//GEN-LAST:event_buttonCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textFieldAcc;
    // End of variables declaration//GEN-END:variables
}
