/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Kinchit
 */
public class CreateAccount extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldPIN = new javax.swing.JTextField();
        textFieldPINAgain = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comBoxAccType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldBalance = new javax.swing.JTextField();
        buttonCreate = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textFieldAddr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textFieldPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldPAN = new javax.swing.JTextField();
        textFieldAadhaar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/icons8-bank-account-32.png"))); // NOI18N
        jLabel1.setText("Enter Details");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(47, 183, 0, 0);
        add(jLabel1, gridBagConstraints);

        textFieldName.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 154);
        add(textFieldName, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 183, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 203, 0, 0);
        add(jLabel3, gridBagConstraints);

        textFieldPIN.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        textFieldPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldPINKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 154);
        add(textFieldPIN, gridBagConstraints);

        textFieldPINAgain.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 154);
        add(textFieldPINAgain, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel4.setText("Confirm PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 129, 0, 0);
        add(jLabel4, gridBagConstraints);

        comBoxAccType.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        comBoxAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Current" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 154);
        add(comBoxAccType, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel5.setText("Account Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 114, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel6.setText("Opening Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 89, 0, 0);
        add(jLabel6, gridBagConstraints);

        textFieldBalance.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 154);
        add(textFieldBalance, gridBagConstraints);

        buttonCreate.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        buttonCreate.setText("Create Account");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 183, 62, 0);
        add(buttonCreate, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel7.setText("Address");
        jLabel7.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 164, 0, 0);
        add(jLabel7, gridBagConstraints);

        textFieldAddr.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 154);
        add(textFieldAddr, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel8.setText("Phone Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 106, 0, 0);
        add(jLabel8, gridBagConstraints);

        textFieldPhone.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 154);
        add(textFieldPhone, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel9.setText("PAN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 196, 0, 0);
        add(jLabel9, gridBagConstraints);

        textFieldPAN.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 154);
        add(textFieldPAN, gridBagConstraints);

        textFieldAadhaar.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 128;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 154);
        add(textFieldAadhaar, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel10.setText("Aadhaar No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 132, 0, 0);
        add(jLabel10, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldPINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPINKeyTyped
        // TODO add your handling code here:
        if(textFieldPIN.getText().length()>5){
            textFieldPIN.setText(textFieldPIN.getText().substring(0, 3));
        }
    }//GEN-LAST:event_textFieldPINKeyTyped

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        // TODO add your handling code here:
        String acc="";
        try{
            Connection con=DriverManager.getConnection(ATM.url);
            con.setAutoCommit(false);
            Statement statement=con.createStatement();
            String sql="select acc_no from accounts";
            ResultSet res=statement.executeQuery(sql);
            while(res.next()){
                acc=ATM.getNumericString(11);
                if(acc.equals(res.getString(1))) acc=ATM.getNumericString(11);
            }
            sql="select c_id from customers order by c_id desc limit 1";
            res=statement.executeQuery(sql);
            res.next();
            int c_id=res.getInt(1)+1;
            sql="insert into customers values(?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setInt(1, c_id);
            ps.setString(2,textFieldName.getText());
            ps.setString(3, textFieldAddr.getText());
            String phone=textFieldPhone.getText();
            if(!Pattern.matches("^\\d{10}$",phone)){
                JOptionPane.showMessageDialog(this, "Phone Number Invalid", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ps.setString(4, phone);
            String pan=textFieldPAN.getText();
            if(!Pattern.matches(ATM.regexPAN,pan)){
                JOptionPane.showMessageDialog(this, "PAN Invalid", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ps.setString(5, pan);
            String aadhaar=textFieldAadhaar.getText();
            if(!Pattern.matches(ATM.regexAadhaar,aadhaar));
            ps.setString(6,aadhaar);
            if(ps.executeUpdate()!=1){
                JOptionPane.showMessageDialog(this, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql="insert into accounts values(?,?,?,?,?,?,?)";
            ps=con.prepareStatement(sql);
            ps.setString(1,acc);
            ps.setString(2, textFieldPIN.getText());
            ps.setString(3,textFieldName.getText());
            ps.setString(4, comBoxAccType.getSelectedItem().toString().toLowerCase());
            ps.setInt(5, Integer.parseInt(textFieldBalance.getText()));
            ps.setInt(6, c_id);
            ps.setInt(7,1);
            if(ps.executeUpdate()!=1){
                JOptionPane.showMessageDialog(this, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }con.commit();
            JOptionPane.showMessageDialog(this, "Account No:"+acc+" created successfully","",JOptionPane.INFORMATION_MESSAGE);
            ATM.panelSwap(this, new Home());
        }catch(HeadlessException | NumberFormatException | SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JComboBox<String> comBoxAccType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textFieldAadhaar;
    private javax.swing.JTextField textFieldAddr;
    private javax.swing.JTextField textFieldBalance;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPAN;
    private javax.swing.JTextField textFieldPIN;
    private javax.swing.JTextField textFieldPINAgain;
    private javax.swing.JTextField textFieldPhone;
    // End of variables declaration//GEN-END:variables
}
