/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.regex.*;

/**
 *
 * @author Kinchit
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TextFieldAcc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ButtonLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TextFieldPIN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.GridBagLayout());

        TextFieldAcc.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        TextFieldAcc.setName("TextFieldAcc"); // NOI18N
        TextFieldAcc.setPreferredSize(new java.awt.Dimension(80, 33));
        TextFieldAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAccActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 125);
        add(TextFieldAcc, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Account No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 146, 0, 0);
        add(jLabel2, gridBagConstraints);

        ButtonLogin.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        ButtonLogin.setText("Check");
        ButtonLogin.setName("ButtonLogin"); // NOI18N
        ButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonLoginMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 208, 174, 0);
        add(ButtonLogin, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("PIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 217, 0, 0);
        add(jLabel3, gridBagConstraints);

        TextFieldPIN.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        TextFieldPIN.setActionCommand("<Not Set>");
        TextFieldPIN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldPIN.setEnabled(false);
        TextFieldPIN.setName("TextFieldAcc"); // NOI18N
        TextFieldPIN.setPreferredSize(new java.awt.Dimension(80, 33));
        TextFieldPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPINActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 125);
        add(TextFieldPIN, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Inter", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(111, 212, 0, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLoginMouseClicked
        if(TextFieldPIN.isEnabled()==false){
            if("0000".equals(TextFieldAcc.getText())){
                ButtonLogin.setText("Login");
                TextFieldAcc.disable();
                TextFieldPIN.enable();
                return;
            }
            if (!Pattern.matches("^\\d{9,18}$",TextFieldAcc.getText())) {
                JOptionPane.showMessageDialog(this,"Enter Valid Account No.","Login",JOptionPane.ERROR_MESSAGE);
                return;
            }
            try{
                Class.forName(ATM.driver);
                String acc_no=TextFieldAcc.getText();
                Connection con = DriverManager.getConnection(ATM.url);
                Statement statement=con.createStatement();
                String sql="select name from accounts where acc_no='"+acc_no+"'";
                ResultSet res=statement.executeQuery(sql);
                if (!res.next()) {
                    JOptionPane.showMessageDialog(this,"Account not found","Login",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(this,res.getString(1),"Account Name",JOptionPane.ERROR_MESSAGE);
                ButtonLogin.setText("Login");
                TextFieldPIN.enable();
                TextFieldAcc.disable();
                return;
            }catch(SQLException | ClassNotFoundException e){
                System.err.println(e);
            }
            
        }
        if (TextFieldPIN.isEnabled()) {
            if(TextFieldPIN.getText().equals("0000")){
                JOptionPane.showMessageDialog(this,"Welcome, Admin","Login",JOptionPane.PLAIN_MESSAGE);
                AdminPanel panel = new AdminPanel();
                ATM.panelSwap(this, panel);
                return;
            }
            if(!Pattern.matches("^\\d{4}$", TextFieldPIN.getText())){
                JOptionPane.showMessageDialog(this,"PIN Invalid","Login",JOptionPane.ERROR_MESSAGE);
                return;
            }
            try {
                Class.forName(ATM.driver);
                String acc_no = TextFieldAcc.getText();
                String pin = TextFieldPIN.getText();
                Connection con = DriverManager.getConnection(ATM.url);
                Statement statement = con.createStatement();
                String sql = "select pin from accounts where acc_no='" + acc_no + "'";
                ResultSet res = statement.executeQuery(sql);
                if (!res.next()) {
                    JOptionPane.showMessageDialog(this,"Account Not Found","Login",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (pin.equals(res.getString("pin"))) {
                    JOptionPane.showMessageDialog(this,"Success","Login",JOptionPane.PLAIN_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this,"PIN Invalid","Login",JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException | ClassNotFoundException e) {
                System.err.println(e.toString());
            }
        }
    }//GEN-LAST:event_ButtonLoginMouseClicked

    private void TextFieldPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPINActionPerformed

    private void TextFieldAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin;
    private javax.swing.JTextField TextFieldAcc;
    private javax.swing.JTextField TextFieldPIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
