/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;

import java.awt.HeadlessException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kinchit
 */
public class Transfer extends javax.swing.JPanel {
    private String acc_no="";
    /**
     * Creates new form Transfer
     * @param acc_no
     */
    public Transfer(String acc_no) {
        this.acc_no=acc_no;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        textFieldInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonTransfer = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/icons8-bank-transfer-32.png"))); // NOI18N
        jLabel1.setText("Transfer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 156, 0, 0);
        add(jLabel1, gridBagConstraints);

        textFieldInput.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        textFieldInput.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 26);
        add(textFieldInput, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Enter payee's account no:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 36, 0, 0);
        add(jLabel2, gridBagConstraints);

        textFieldAmount.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        textFieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAmountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 1, 0, 0);
        add(textFieldAmount, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 185, 0, 0);
        add(jLabel3, gridBagConstraints);

        buttonTransfer.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        buttonTransfer.setText("Send");
        buttonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 185, 35, 0);
        add(buttonTransfer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAmountActionPerformed

    private void buttonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferActionPerformed
        // TODO add your handling code here:
        if (!Pattern.matches(ATM.regexAmount, textFieldAmount.getText())) {
            JOptionPane.showMessageDialog(buttonTransfer, "Please enter a valid amount", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if(!Pattern.matches(ATM.regexAcc, textFieldInput.getText())){
            JOptionPane.showMessageDialog(buttonTransfer, "Please enter a valid account no.", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long amount=Long.parseLong(textFieldAmount.getText());
        try{
            String payeeAcc=textFieldInput.getText();
            Connection con=DriverManager.getConnection(ATM.url);
            con.setAutoCommit(false);
            String sql="select balance from accounts where acc_no='"+acc_no+"'";
            Statement statement=con.createStatement();
            ResultSet res=statement.executeQuery(sql);
            res.next();
            long payerBal=res.getLong(1);
            long newPayerBal=payerBal-amount;
            sql="select name, balance from accounts where acc_no='"+payeeAcc+"'";
            res=statement.executeQuery(sql);
            if(!res.next()){
                JOptionPane.showMessageDialog(buttonTransfer, "Account not found","", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String payeeName=res.getString(1);
            Long payeeBal=res.getLong(2);
            Long newPayeeBal=payeeBal+amount;
            sql="update accounts set balance="+newPayerBal+" where acc_no='"+acc_no+"'";
            int flag=statement.executeUpdate(sql);
            if (flag != 1) {
                JOptionPane.showMessageDialog(buttonTransfer, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql="update accounts set balance="+newPayeeBal+" where acc_no='"+payeeAcc+"'";
            flag=statement.executeUpdate(sql);
            if (flag != 1) {
                JOptionPane.showMessageDialog(buttonTransfer, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql="select count(*) from transactions";
            res=statement.executeQuery(sql);
            res.next();
            int count=res.getInt(1)+1;
            sql="insert into transactions values(?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setInt(1,count);
            ps.setString(2,acc_no);
            ps.setDate(3, Date.valueOf(LocalDate.now()));
            ps.setTime(4, Time.valueOf(LocalTime.now()));
            ps.setString(5, "credit");
            ps.setString(6, payeeName);
            ps.setLong(7, amount);
            flag=ps.executeUpdate();
            if (flag != 1) {
                JOptionPane.showMessageDialog(buttonTransfer, "Transaction Failed", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(buttonTransfer, "Transaction Successful\nReceipt will be generated", this.getName(), JOptionPane.INFORMATION_MESSAGE);
            String reportPath = "C:\\Users\\Kinchit\\JaspersoftWorkspace\\MyReports\\Transfer.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            HashMap param = new HashMap();
            param.put("t_id", count);
            param.put("payee",payeeName);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jv.enable();
            jv.setVisible(true);
            con.commit();
            ATM.panelSwap(this, new Home());
        }catch(HeadlessException | SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(buttonTransfer,"Transaction Failed","",JOptionPane.ERROR_MESSAGE );
        } catch (JRException ex) {
            Logger.getLogger(Transfer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonTransferActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textFieldAmount;
    private javax.swing.JTextField textFieldInput;
    // End of variables declaration//GEN-END:variables
}
