/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package atm;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.regex.Pattern;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kinchit
 */
public class Withdraw extends javax.swing.JPanel {
    private String acc_no;
    /**
     * Creates new form Withdraw
     */
    public Withdraw(String acc_no) {
        this.acc_no=acc_no;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        TextFieldAmount = new javax.swing.JTextField();
        ButtonWithdraw = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("Amount:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 123, 0, 0);
        add(jLabel3, gridBagConstraints);

        TextFieldAmount.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 131);
        add(TextFieldAmount, gridBagConstraints);

        ButtonWithdraw.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        ButtonWithdraw.setText("Withdraw");
        ButtonWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonWithdrawMouseClicked(evt);
            }
        });
        ButtonWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWithdrawActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 169, 37, 0);
        add(ButtonWithdraw, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/icons8-withdraw-32.png"))); // NOI18N
        jLabel4.setText("Withdraw");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 159, 0, 0);
        add(jLabel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonWithdrawMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ButtonWithdrawMouseClicked

    private void ButtonWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWithdrawActionPerformed
        // TODO add your handling code here:
        if (!Pattern.matches(ATM.regexAmount, TextFieldAmount.getText())) {
            JOptionPane.showMessageDialog(ButtonWithdraw, "Please enter a valid amount", "Withdraw", JOptionPane.ERROR_MESSAGE);
            return;
        }
        long amount = Long.parseLong(TextFieldAmount.getText());
        try {
            Connection con = DriverManager.getConnection(ATM.url);
            con.setAutoCommit(false);
            String sql = "select balance from accounts where acc_no=" + acc_no;
            Statement statement = con.createStatement();
            ResultSet res = statement.executeQuery(sql);
            res.next();
            long balance = res.getLong(1);
            long newBalance = balance - amount;
            sql = "update accounts set balance=" + newBalance + " where acc_no=" + acc_no;
            int flag = statement.executeUpdate(sql);
            if (flag != 1) {
                JOptionPane.showMessageDialog(ButtonWithdraw, "Transaction Failed", "Withdraw", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql = "select balance from accounts where acc_no='0000'";
            res = statement.executeQuery(sql);
            res.next();
            long cash = res.getLong(1);
            cash = cash - amount;
            sql = "update accounts set balance=" + cash + " where acc_no='0000'";
            flag = statement.executeUpdate(sql);
            if (flag != 1) {
                JOptionPane.showMessageDialog(ButtonWithdraw, "Transaction Failed", "Withdraw", JOptionPane.ERROR_MESSAGE);
                return;
            }
            sql = "select count(*) from transactions";
            ResultSet result = statement.executeQuery(sql);
            result.next();
            int count = result.getInt(1);
            count++;
            sql = "insert into transactions values(?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, count);
            ps.setString(2, acc_no);
            ps.setDate(3, Date.valueOf(LocalDate.now()));
            ps.setTime(4, Time.valueOf(LocalTime.now()));
            ps.setString(5, "credit");
            ps.setString(6, "self");
            ps.setLong(7, amount);
            flag = ps.executeUpdate();
            if (flag != 1) {
                JOptionPane.showMessageDialog(ButtonWithdraw, "Transaction Failed", "Withdraw", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Transaction Successful\nReceipt will be generated", this.getName(), JOptionPane.INFORMATION_MESSAGE);
            String reportPath = "C:\\Users\\Kinchit\\JaspersoftWorkspace\\MyReports\\Receipt.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            HashMap param = new HashMap();
            param.put("t_id", count);
            JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jv.enable();
            jv.setVisible(true);
            con.commit();
            ATM.panelSwap(this, new Home());

        } catch (SQLException e) {
            e.printStackTrace();
        } catch (JRException ex) {
            Logger.getLogger(Withdraw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonWithdrawActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonWithdraw;
    private javax.swing.JTextField TextFieldAmount;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
